Test2/XAppointment/Controllers/ItemGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using XAppointment.Models;

namespace XAppointment.Controllers
{
    public class ItemGroupController : Controller
    {
		SqlConnection con = new SqlConnection("Server=192.168.0.27;Database=XAppoinment;User Id=sa; Password=123456;");
		SqlCommand com;
        public ActionResult Index()
        {
            com = new SqlCommand("SELECT cate_ItemCategoryID, cate_Name FROM tblItemCategory", con);
            List<ItemSizeModel> list = new List<ItemSizeModel>();
            SqlDataReader reader;

            try
            {
                con.Open();
                reader = com.ExecuteReader();
                while (reader.Read())
                {
                    list.Add(new ItemSizeModel()
                    {
                        size = int.Parse(reader["cate_ItemCategoryID"].ToString()),
                        sName = reader["cate_Name"].ToString()
                    });
                }
                ViewData["Cate"] = list;
                reader.Close();

                com = new SqlCommand("SELECT itmg_ItemGroupID, itmg_Name FROM tblItemGroup", con);
                reader = com.ExecuteReader();
                List<ItemSizeModel> lis = new List<ItemSizeModel>();
                while (reader.Read())
                {
                    lis.Add(new ItemSizeModel(){
                        size=int.Parse(reader["itmg_ItemGroupID"].ToString()),
                        sName=reader["itmg_Name"].ToString()
                    });
                }
                ViewData["itG"] = lis;
                reader.Close();

				com = new SqlCommand("SELECT WorkFlowID ,Name FROM sys_workflow", con);
                List<ItemSizeModel> lwf = new List<ItemSizeModel>();
                reader = com.ExecuteReader();
                while (reader.Read())
                {
                    lwf.Add(new ItemSizeModel()
                    {
                        size = int.Parse(reader["WorkFlowID"].ToString()),
                        sName=reader["Name"].ToString()
                    });
                }
                ViewData["lwf"] = lwf;
                reader.Close();

				com = new SqlCommand("SELECT WorkFlowStateID ,State FROM sys_workflowstate", con);
                List<ItemSizeModel> ls = new List<ItemSizeModel>();
                reader = com.ExecuteReader();
                while (reader.Read())
                {
                    ls.Add(new ItemSizeModel(){
                        size=int.Parse(reader["WorkFlowStateID"].ToString()),
                        sName=reader["State"].ToString()
                    });
                }
                ViewData["ls"] = ls;
                reader.Close();


            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            finally{
                con.Close();
            }

            return View ();
        }

        public ActionResult SaveDB(){

            com = new SqlCommand("INSERT INTO tblItemGroup(itmg_WorkFlowID, itmg_StateID, itmg_CreatedDate, itmg_Name" +
                                 ", itmg_ParentGroup, itmg_ItemCategoryID) VALUES(@iwf, @sid, GETDATE(), @iN, @ipg, @iici)", con);
            com.Parameters.AddWithValue("@iwf", Request.Form["idWorkFlow"]);
            com.Parameters.AddWithValue("@sid", Request.Form["idState"]);
            com.Parameters.AddWithValue("@iN", Request.Form["inName"]);
            com.Parameters.AddWithValue("@ipg", Request.Form["pg"]);
            com.Parameters.AddWithValue("@iici", Request.Form["c"]);

            try
            {
                con.Open();
                com.ExecuteNonQuery();

            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            finally{
                con.Close();
            }
            return View();
        }

        public ActionResult ItemGroupList(){

            if (Request.Form["del"]!=null)
            {
                com = new SqlCommand("DELETE FROM tblItemGroup where itmg_ItemGroupID=@id", con);
                com.Parameters.AddWithValue("@id", Request.Form["del"]);
                try
                {
                    con.Open();
                    com.ExecuteNonQuery();
                }
                catch (Exception ex)
                {
                    Response.Write(ex.Message);
                }
                finally{
                    con.Close();
                }
            }
            com = new SqlCommand("SELECT  itmg_ItemGroupID, (SELECT Name FROM sys_workflow WHERE itmg_WorkFlowID=WorkFlowID)AS 'WorkFlow',(select [state] from sys_workflowstate where WorkFlowStateID=itmg_StateID )as 'State', " +
                                 "itmg_CreatedDate, itmg_Name, (SELECT cate_Name FROM tblItemCategory WHERE cate_ItemCategoryID=itmg_ItemCategoryID)AS 'Category' FROM tblItemGroup", con);
            List<ItemGroupListModel> il = new List<ItemGroupListModel>();
            try
            {
                con.Open();
                SqlDataReader reader = com.ExecuteReader();
                int i = 0;
                while (reader.Read())
                {
                    il.Add(new ItemGroupListModel()
                    {
                        ID = i,
                        iID=int.Parse(reader["itmg_ItemGroupID"].ToString()),
                        WorkFlow=reader.IsDBNull(1)?"":reader["WorkFlow"].ToString(),
                        State=reader.IsDBNull(2)?"": reader["State"].ToString(),
                        CreatedDate= reader.IsDBNull(3)?"": reader["itmg_CreatedDate"].ToString(),
                        Name= reader.IsDBNull(4)?"" : reader["itmg_Name"].ToString(),
                        Category= reader.IsDBNull(5)?"" : reader["Category"].ToString()
                    });
                    i++;
                }

				string param = "0";
                float lcount = il.Count / 5;
				if (Request.Form["inn"] != null && int.Parse(Request.Form["inn"]) < (int)lcount)
				{
					param = (int.Parse(Request.Form["inn"].ToString()) + 1).ToString();
				}
				else if (Request.Form["idPre"] != null && int.Parse(Request.Form["idPre"]) >= 1)
				{
					param = (int.Parse(Request.Form["idPre"].ToString()) - 1).ToString();
				}

				ViewData["next"] = param;
				ViewData["prev"] = param;
                ViewData["il"] = il.Where(l => l.ID >= int.Parse(param) * 5).Take(5); 

            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            return View();
        }
         


        public ActionResult UpdateDB(){
			SqlDataReader reader;


			try
			{
                con.Open();

                com = new SqlCommand("SELECT itmg_ItemGroupID, itmg_WorkFlowID, itmg_StateID, itmg_Name, itmg_ItemCategoryID FROM tblItemGroup WHERE itmg_ItemGroupID=@id", con);
                com.Parameters.AddWithValue("@id", Request.Form["edits"]);
                List<ItemGroupListModel> iglm = new List<ItemGroupListModel>();
                reader = com.ExecuteReader();
                int i = 0;
                while (reader.Read())
                {
                    iglm.Add(new ItemGroupListModel()
                    {
                        ID = i,
                        iID=int.Parse(reader["itmg_ItemGroupID"].ToString()),
                        WorkFlow=reader["itmg_WorkFlowID"].ToString(),
                        State=reader["itmg_StateID"].ToString(),
                        Name=reader["itmg_Name"].ToString(),
                        Category=reader["itmg_ItemCategoryID"].ToString()

                    });
                    i++;
                }
                ViewData["boom"] = iglm;
                reader.Close(); 

                com = new SqlCommand("SELECT cate_ItemCategoryID, cate_Name FROM tblItemCategory", con);
				List<ItemSizeModel> list = new List<ItemSizeModel>();
				reader = com.ExecuteReader();
				while (reader.Read())
				{
					list.Add(new ItemSizeModel()
					{
						size = int.Parse(reader["cate_ItemCategoryID"].ToString()),
						sName = reader["cate_Name"].ToString()
					});
				}
				ViewData["Cate"] = list;
				reader.Close();

				com = new SqlCommand("SELECT itmg_ItemGroupID, itmg_Name FROM tblItemGroup", con);
				reader = com.ExecuteReader();
				List<ItemSizeModel> lis = new List<ItemSizeModel>();
				while (reader.Read())
				{
					lis.Add(new ItemSizeModel()
					{
						size = int.Parse(reader["itmg_ItemGroupID"].ToString()),
						sName = reader["itmg_Name"].ToString()
					});
				}
				ViewData["itG"] = lis;
				reader.Close();

				com = new SqlCommand("SELECT WorkFlowID ,Name FROM sys_workflow", con);
				List<ItemSizeModel> lwf = new List<ItemSizeModel>();
				reader = com.ExecuteReader();
				while (reader.Read())
				{
					lwf.Add(new ItemSizeModel()
					{
						size = int.Parse(reader["WorkFlowID"].ToString()),
						sName = reader["Name"].ToString()
					});
				}
				ViewData["lwf"] = lwf;
				reader.Close();

				com = new SqlCommand("SELECT WorkFlowStateID ,State FROM sys_workflowstate", con);
				List<ItemSizeModel> ls = new List<ItemSizeModel>();
				reader = com.ExecuteReader();
				while (reader.Read())
				{
					ls.Add(new ItemSizeModel()
					{
						size = int.Parse(reader["WorkFlowStateID"].ToString()),
						sName = reader["State"].ToString()
					});
				}
				ViewData["ls"] = ls;
				reader.Close();


			}
			catch (Exception ex)
			{
				Response.Write(ex.Message);
			}
			finally
			{
				con.Close();
			}

			return View();
        }
    }
}

Test2/XAppointment/Views/ItemGroup/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>X-Appointment</title>
    <meta charset="UTF-8"/>
    <link href="~/Scripts/css/metro.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-icons.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-schemes.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/metro.js"></script>
    <script src="~/Scripts/js/metro.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

        <script></script>
        <style>
        
        footer{
            position:absolute;
            right:0;
            bottom:0;
            left:0;
            text-align: center;
            background-color: gray;
            color:white;
            padding:1em;
            clear:bottom;
        }
        
        header{
            background-color: gray;
            text-align: center;
            color: white;
            padding: 1em;
            clear: left;
        }
        
        .Container{
            position:absolute;
            left:30%;
            top:25em;
        }

        #inName{
            padding: 20em;
            clear: left;
        }

        label{
            padding:1em;
        }

        #btnSave{
            left:18%;
        }
        .imG{
            position:absolute;
            left:40%;
        }

        .item{
            position:absolute;
            top:24em;
            align:center;
            left:33%;
        }
        .setting{
            position:fixed;      
            align:center;
            top:35em;
            left:35%;
        }
        h3{
            background-color:transparent;
            
        }
        span {
            color: red;
        }
        
    </style>
        
</head>
<body>
        <header>
        <h3>Welcome to X-Apointment system</h3>
    </header>
        <h4 align="center" style="padding-top:15%">
        <form id="frmSub" action="@Url.Action("SaveDB","ItemGroup")" method="post">
                <label>Work flow</label>
        <select name="idWorkFlow" >
					@{
					    foreach(var item in ViewBag.lwf){
                            <option value="@item.size">@item.sName</option>
					}}
        </select>
        <label>State</label>
        <select name="idState" >
					@{
                    foreach(var item in ViewBag.ls){
                        <option value="@item.size">@item.sName</option>
					}}
        </select>
        <br><br><br>
                <label>Parent Group</label>
				<select name="pg">
					@{
					foreach(var item in ViewBag.itG){
                        <option value="@item.size">@item.sName</option>    
					}
                        
					}
				</select>
				<label>Category</label>
				<select name="c">
					@{
					    foreach(var item in ViewBag.Cate){
                            <option value="@item.size">@item.sName</option>
					    }
					}
				</select>            <br><br><br>
				
                <input id="inNa" name="inName" type="text" class="input-control text" placeholder="Group Name"/>
                <!--<input id="inAddress" name="inAddre" type="text" class="input-control text" placeholder="Address"/>-->
                

                <input type="submit" value="Save" align="center" class="button success"/>
            </form>
            </h4>
        <h3 align="center">
        <form action="@Url.Action("ItemGroupList","ItemGroup")" method="post">
            <input type="submit" value="View Item Group list"/>
        </form>
            </h3>
    <footer>Copyright &copy; X-ware.com</footer>
        <script>
           $("#frmSub").submit(function(event){
                if ($("#inNa").val()==="") {
                    $("#inNa").addClass("error");
                }else
                    $("#inNa").removeClass("error");
            

                if ($("#inNa").val()==="" ) {
                    event.preventDefault();
                    return;
                }
            })
        </script>
</body>
</html>

Test2/XAppointment/Views/ItemGroup/ItemGroupList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>ItemGroupList</title>
		<meta charset="UTF-8"/>
    <link href="~/Scripts/css/metro.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-icons.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-schemes.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/metro.js"></script>
    <script src="~/Scripts/js/metro.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<script></script>
        <style>
        
        footer{
            position:absolute;
            right:0;
            bottom:0;
            left:0;
            text-align: center;
            background-color: gray;
            color:white;
            padding:1em;
            clear:bottom;
        }
        
        header{
            background-color: gray;
            text-align: center;
            color: white;
            padding: 1em;
            clear: left;
        }
        
        .Container{
            position:absolute;
            left:30%;
            top:25em;
        }

        #inName{
            padding: 20em;
            clear: left;
        }

        label{
            padding:1em;
        }

        #btnSave{
            left:18%;
        }
        .imG{
            position:absolute;
            left:40%;
        }

        .item{
            position:absolute;
            top:24em;
            align:center;
            left:33%;
        }
        .setting{
            position:fixed;      
            align:center;
            top:35em;
            left:35%;
        }
        h3{
            background-color:transparent;
            
        }
        span {
            color: red;
        }
        
    </style>
</head>
<body>
		<header>
        <h3>Welcome to X-Apointment system</h3>
    </header>

		<form action="@Url.Action("","")">
			<h3 align="center">item group list</h3>
        <table class="table striped hovered ">
            <thead>
                <tr>
                    <td>
                        <label>ID</label>
                    </td>
                    <td><label>Work Flow</label>
                    </td>
                    <td><label>State</label></td>
                    <td><label>Created Date</label></td>
                    <td><label>Name</label></td>
                    <td><label>Category</label></td>
						<td align="right" colspan="3"><label>Other</label></td>
                </tr>
            </thead>
            <tbody>
                @{
                foreach(var item in ViewBag.il){
                <tr>
                    <td>@item.iID</td>
                    <td>@item.WorkFlow</td>
                    <td>@item.State</td>
                    <td>@item.CreatedDate</td>
                    <td>@item.Name</td>
                    <td>@item.Category</td>
						<td align="right">
                            <form action="@Url.Action("UpdateDB","ItemGroup")" method="post">
                                <input type="submit" value="Edit" class="button link"/>
								<input type="hidden" name="edits" value="@item.iID"/>
                            </form>
                    </td>
                        <td align="left">
                            <form action="@Url.Action("ItemGroupList","ItemGroup")" method="post">
                                <input type="submit" value="Delete" class="button link"/>
								<input type="hidden" name="del" value="@item.iID"/>
                            </form>
                        </td>
                </tr>
                }}
                <tr>
                        <td align="right" colspan="4">
							<form action="@Url.Action("ItemGroupList","ItemGroup")" method="post">
                                <input type="submit" value="Previous"/>
                                <input type="hidden" value="@ViewBag.prev" name="idPre"/>
							</form>
						</td>
						<td align="center" colspan="1">
							<form action="@Url.Action("Index","ItemGroup")">
								<input type="submit" value="Add New"/>
							</form>                     
						</td>
						<td align="left" colspan="4">
							<form action="@Url.Action("ItemGroupList","ItemGroup")" method="post">
								<input type="submit" value="Next"/>
								<input type="hidden" value="@ViewBag.next" name="inn"/>
							</form>
						</td>
                </tr>
            </tbody>
        </table>
		</form>      
		<footer>Copyright &copy; X-ware.com</footer>
</body>
</html>

Test2/XAppointment/Views/ItemGroup/SaveDB.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head><title>X-Appointment</title>
    <meta charset="UTF-8"/>
    <link href="~/Scripts/css/metro.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-icons.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-schemes.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/metro.js"></script>
    <script src="~/Scripts/js/metro.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body><h4 align="center">
		<form action="@Url.Action("Index","ItemGroup")" method="post">
			<input type="submit" value="Save"/>
		</form>
		<form action="@Url.Action("ItemGroupList","ItemGroup")" method="post">
			<input type="submit" value="Show Item List"/>
		</form>
			</h4>
</body>
</html>

Test2/XAppointment/Views/ItemGroup/UpdateDB.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>X-Appointment</title>
    <meta charset="UTF-8"/>
    <link href="~/Scripts/css/metro.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-icons.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/metro-schemes.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/js/metro.js"></script>
    <script src="~/Scripts/js/metro.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

        <script></script>
        <style>
        
        footer{
            position:absolute;
            right:0;
            bottom:0;
            left:0;
            text-align: center;
            background-color: gray;
            color:white;
            padding:1em;
            clear:bottom;
        }
        
        header{
            background-color: gray;
            text-align: center;
            color: white;
            padding: 1em;
            clear: left;
        }
        
        .Container{
            position:absolute;
            left:30%;
            top:25em;
        }

        #inName{
            padding: 20em;
            clear: left;
        }

        label{
            padding:1em;
        }

        #btnSave{
            left:18%;
        }
        .imG{
            position:absolute;
            left:40%;
        }

        .item{
            position:absolute;
            top:24em;
            align:center;
            left:33%;
        }
			
        .setting{
            position:fixed;      
            align:center;
            top:35em;
            left:35%;
        }
			
        h3{
            background-color:transparent;
            
        }
			
        span {
            color: red;
        }
        
    </style>
        
</head>
<body>
        <header>
        <h3>Welcome to X-Apointment system</h3>
    </header>

        <h4 align="center" style="padding-top:15%">
			<label style="color:red;">Update Data</label>
			<br>
                <br>
        <form id="frmSub" action="@Url.Action("SaveDB","ItemGroup")" method="post">
                <label>Work flow</label>
				
        <select name="idWorkFlow" >
                    @{
                        foreach(var item in ViewBag.lwf){
					    if (item.size==int.Parse(ViewBag.boom[0].WorkFlow.ToString())) {
					        <option value="@item.size" selected>@item.sName</option>
					    }else {
					        <option value="@item.size">@item.sName</option>
					    }
                    }}
        </select>
        <label>State</label>
        <select name="idState" >
                    @{
                    foreach(var item in ViewBag.ls){
					    if (item.size==int.Parse(ViewBag.boom[0].State.ToString())) {
					        <option value="@item.size" selected>@item.sName</option>
					    }else {
					        <option value="@item.size">@item.sName</option>
					    }
                    }}
        </select>
        <br><br><br>
                <label>Parent Group</label>
                <select name="pg">
                    @{
                    foreach(var item in ViewBag.itG){
					    if (item.size==ViewBag.boom[0].iID) {
					        <option value="@item.size" selected>@item.sName</option>
					    }else {
					        <option value="@item.size">@item.sName</option>
					    }
                    }
                    }
                </select>
                <label>Category</label>
                <select name="c">
                    @{
                        foreach(var item in ViewBag.Cate){
					        if (item.size==int.Parse(ViewBag.boom[0].Category.ToString())) {
					            <option value="@item.size.ToString()" selected>@item.sName.ToString()</option>
					        }else {
					            <option value="@item.size.ToString()">@item.sName.ToString()</option>
					        }
                        }
                    }
                </select>            <br><br><br>
                
                <input id="inNa" name="inName" type="text" class="input-control text" placeholder="Group Name"/>
                <!--<input id="inAddress" name="inAddre" type="text" class="input-control text" placeholder="Address"/>-->
                

                <input type="submit" value="Save" align="center" class="button success"/>
            </form>
            </h4>
        <h3 align="center">
        <form action="@Url.Action("ItemGroupList","ItemGroup")" method="post">
            <input type="submit" value="View Item Group list"/>
        </form>
            </h3>
    
</body>
</html>