Test2/Test3/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test3.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            ViewData["s"] = "About Controller Data";
            return View ("ViewData");
        }
    }
}

Test2/Test3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

namespace Test3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //var mvcName = typeof(Controller).Assembly.GetName();
            //var isMono = Type.GetType("Mono.Runtime") != null;

            //ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            //ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            ViewData["s"] = "Data Home";


            return View();
        }
    }
}

Test2/Test3/Controllers/ViewAboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test3.Controllers
{
    public class ViewAboutController : Controller
    {
        public ActionResult Index()
        {
            ViewData["s"] = "View About Data";
            return View ();
        }
    }
}

Test2/Test3/Views/About/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Index</title>
</head>
<body>
		<h2>Welcome to about</h2>
		<h2>@ViewBag.s</h2>
        
		<form action="@Url.Action("Index","ViewAbout")" method="post">
			<input type="submit" value="View About"/>
		</form>
</body>
</html>


Test2/Test3/Views/About/ViewData.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>ViewData</title>
</head>
<body>
		<h2>Welcome to About 2</h2>
		<h2>@ViewBag.s</h2>
</body>
</html>
